name: Mirror & Filter to Public
on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror with filter
        uses: usherlabs/monorepo-package-mirror-action@v1.0.0
        with:
          target_repo_url: git@github.com:Hashory/24saikyou-jam.git
          ssh_private_key: ${{ secrets.MIRROR_SSH_KEY }}
